version: "3.8"

services:
  mysql:
    image: "bitnami/mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'db_app'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

# learn again bot this...
  app:
    tty: true
    build: .
    command: nodemon index.js
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/app